# Generated by Django 4.2.11 on 2024-05-22 01:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        ('project', '0021_icon_svg_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('avatar', models.ImageField(upload_to='author_avatars/', verbose_name='Аватар')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('publication_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('category', models.CharField(choices=[('blog', 'Блог'), ('analytics', 'Аналитика')], max_length=10, verbose_name='Категория')),
                ('rating', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Рейтинг')),
                ('user_rating', models.FloatField(default=0.0, editable=False, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Пользовательский рейтинг')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.author', verbose_name='Автор')),
                ('project', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='project.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ArticleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='article_blocks/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_blocks', to='news.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Блок новости',
                'verbose_name_plural': 'Блоки новостей',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='news.news')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
                'unique_together': {('session', 'news')},
            },
        ),
    ]
