# Generated by Django 4.2.11 on 2024-04-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jumbotron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=125, verbose_name='Подзаголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('button_link', models.URLField(verbose_name='Ссылка для кнопки')),
                ('picture', models.ImageField(upload_to='jumbotrons/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['order'],
            },
        ),
    ]
