# Generated by Django 4.2.7 on 2024-01-25 14:51

from django.db import migrations, models


def add_default_setting(apps, schema_editor):
    Setting = apps.get_model('setting', 'Setting')
    new_types = [
        Setting(
            phone='8 (800) 222-56-83',
            email='office@lennar.ru',
            legal_entity='ООО "АН ПЕРСПЕКТИВА"',
            inn='9706040146',
            ogrn='1237700897895',
            privacy_policy='https://google.com/',
            data_processing='https://google.com/'
        ),
    ]
    Setting.objects.bulk_create(new_types)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('legal_entity', models.CharField(max_length=255, verbose_name='Юридическое лицо')),
                ('inn', models.CharField(max_length=25, verbose_name='Инн')),
                ('ogrn', models.CharField(max_length=25, verbose_name='Огрн')),
                ('privacy_policy', models.URLField(verbose_name='Политика конфидициальности')),
                ('data_processing', models.URLField(verbose_name='Обработка данных')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.RunPython(add_default_setting),
    ]
