# Generated by Django 4.2.7 on 2024-01-25 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_room_blocked_at_room_is_sold'),
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, to='project.project', verbose_name='Проекты'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='data_processing',
            field=models.FileField(help_text='Можно загрузить файлы: pdf', upload_to='files/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Обработка данных'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='privacy_policy',
            field=models.FileField(help_text='Можно загрузить файлы: pdf', upload_to='files/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Политика конфидициальности'),
        ),
    ]
