# Generated by Django 4.2.7 on 2024-01-19 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_notification_types(apps, schema_editor):
    NotificationType = apps.get_model('notification', 'NotificationType')
    new_types = [
        NotificationType(name='Новые заявки на обратную связь', system_name='feedback'),
    ]
    NotificationType.objects.bulk_create(new_types)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Отображаемое название')),
                ('system_name', models.CharField(max_length=100, verbose_name='Системное название')),
            ],
            options={
                'verbose_name': 'Тип уведомления',
                'verbose_name_plural': 'Типы уведомления',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('enabled_notifications', models.ManyToManyField(blank=True, to='notification.notificationtype', verbose_name='Включенные уведомления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_notification', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление email',
                'verbose_name_plural': 'Уведомления emails',
            },
        ),
        migrations.RunPython(add_notification_types),
    ]
