# Generated by Django 4.2.7 on 2024-01-22 15:23

from django.db import migrations



def add_notification_types(apps, schema_editor):
    NotificationType = apps.get_model('notification', 'NotificationType')
    new_types = [
        NotificationType(name='Новые заявки на бронирование', system_name='reservation'),
    ]
    NotificationType.objects.bulk_create(new_types)


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_notification_types),
    ]
