# Generated by Django 4.2.7 on 2024-01-24 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='Название')),
                ('icon', models.FileField(help_text='Можно загрузить файлы: svg, png, jpg, jpeg', upload_to='bank_icons/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])], verbose_name='Иконка')),
                ('url', models.URLField(verbose_name='Ссылка на сайт')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
            },
        ),
    ]
