# Generated by Django 4.2.11 on 2024-05-03 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHistory',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False, verbose_name='Год')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'История компании',
                'verbose_name_plural': 'Истории компании',
            },
        ),
        migrations.CreateModel(
            name='CompanyHistoryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='history_images/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('company_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='history.companyhistory', verbose_name='История компании')),
            ],
            options={
                'verbose_name': 'Блок истории компании',
                'verbose_name_plural': 'Блоки историй компании',
                'ordering': ['order'],
            },
        ),
    ]
