# Generated by Django 4.2.11 on 2024-06-10 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyhistory',
            options={'ordering': ('-year',), 'verbose_name': 'История компании', 'verbose_name_plural': 'Истории компании'},
        ),
    ]
