# Generated by Django 4.2.11 on 2024-05-15 21:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=150, verbose_name='Должность')),
                ('salary', models.CharField(max_length=150, verbose_name='Зарплата')),
                ('conditions', models.TextField(verbose_name='Условия')),
                ('requirements', models.TextField(verbose_name='Требования')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='JobResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('specialty', models.CharField(blank=True, max_length=255, verbose_name='Специальность')),
                ('resume', models.FileField(upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(('pdf',))], verbose_name='Резюме')),
                ('cover_letter', models.FileField(blank=True, upload_to='cover_letters/', validators=[django.core.validators.FileExtensionValidator(('pdf',))], verbose_name='Сопроводительное письмо')),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_responses', to='career.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
            },
        ),
    ]
