# Generated by Django 4.2.7 on 2024-01-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_latitude_alter_project_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='title',
            field=models.CharField(default=True, max_length=125, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.CharField(default=True, max_length=255, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
