# Generated by Django 4.2.7 on 2024-01-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=125, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
