# Generated by Django 4.2.7 on 2024-01-19 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='Название')),
                ('square', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Площадь')),
                ('room', models.IntegerField(blank=True, default=0, help_text='"Студия" - это пустое поле', null=True, verbose_name='Количество комнат')),
                ('image', models.ImageField(upload_to='layouts/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Планировка',
                'verbose_name_plural': 'Планировки',
            },
        ),
        migrations.AddField(
            model_name='estateobject',
            name='corps',
            field=models.IntegerField(default=0, verbose_name='Корпус'),
        ),
        migrations.AddField(
            model_name='estateobject',
            name='title',
            field=models.CharField(default=True, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat', models.SmallIntegerField(default=0, verbose_name='Квартира')),
                ('floor', models.SmallIntegerField(default=0, verbose_name='Этаж')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена')),
                ('estate_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='project.estateobject', verbose_name='Объект недвижимости')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='project.layout', verbose_name='Планировка')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
    ]
