# Generated by Django 4.2.7 on 2024-01-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_layout_estateobject_corps_estateobject_title_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, max_length=125, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
