# Generated by Django 4.2.7 on 2024-01-19 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_city_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='icon',
            field=models.FileField(upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])], verbose_name='Иконка'),
        ),
    ]
