# Generated by Django 4.2.7 on 2024-01-19 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_icon_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='icon',
            field=models.FileField(help_text='Можно загрузить файлы: svg, png, jpg, jpeg', upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])], verbose_name='Иконка'),
        ),
    ]
