# Generated by Django 4.2.7 on 2024-01-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='blocked_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Заблокировано'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='Продана'),
        ),
    ]
