# Generated by Django 4.2.11 on 2024-04-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_project_tour_3d_url_project_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('housing', 'Жилье'), ('business_space', 'Бизнес-Пространство')], default='housing', max_length=45, verbose_name='Тип'),
        ),
    ]
