# Generated by Django 4.2.11 on 2024-04-18 14:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_alter_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='locations/', verbose_name='Изображение')),
                ('ya_maps_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на яндекс карты')),
            ],
            options={
                'verbose_name': 'Расположение',
                'verbose_name_plural': 'Расположения',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='catalog_btn_link',
            field=models.CharField(blank=True, max_length=125, verbose_name='Ссылка кнопки "Смотреть каталог"'),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_advantages',
            field=models.ManyToManyField(related_name='featured_projects', to='project.advantage', verbose_name='Избранные преимущества'),
        ),
        migrations.AddField(
            model_name='project',
            name='housing_description',
            field=models.TextField(default='', verbose_name='Описание корпусов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='is_catalog_btn_enable',
            field=models.BooleanField(default=False, verbose_name='Ссылка кнопки "Смотреть каталог" активна'),
        ),
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_image',
            field=models.ImageField(blank=True, null=True, upload_to='short_descriptions/', verbose_name='Изображение для краткого описания'),
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='Заголовок')),
                ('horizontal_image', models.ImageField(upload_to='horizontal_text_blocks/', verbose_name='Горизонтальное изображение')),
                ('square_image', models.ImageField(upload_to='square_text_blocks/', verbose_name='Квадратное изображение')),
                ('text', models.TextField(verbose_name='Текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_blocks', to='project.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Универсальный текстовый блок',
                'verbose_name_plural': 'Универсальные текстовые блоки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(help_text='Можно загрузить файлы: svg, png, jpg, jpeg', upload_to='routes/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])], verbose_name='Иконка')),
                ('destination', models.CharField(max_length=30, verbose_name='Точка назначения')),
                ('travel_time', models.CharField(max_length=30, verbose_name='Время в пути')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='project.location', verbose_name='Расположение')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.location', verbose_name='Расположение'),
        ),
    ]
