# Generated by Django 4.2.11 on 2024-04-29 01:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_estateobject_area_max_estateobject_area_min_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icon',
            options={'ordering': ('title',), 'verbose_name': 'Иконка', 'verbose_name_plural': 'Иконки'},
        ),
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.FileField(blank=True, help_text='Можно загрузить файлы: svg, png, jpg, jpeg', upload_to='project_icon/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])], verbose_name='Иконка'),
        ),
        migrations.CreateModel(
            name='Geotag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='Название')),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Долгота')),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Широта')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icon_geotags', to='project.icon', verbose_name='Иконка')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geotags', to='project.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Геометка',
                'verbose_name_plural': 'Геометки',
            },
        ),
    ]
