# Generated by Django 4.2.11 on 2024-05-01 00:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.dates


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_alter_icon_options_project_icon_geotag'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027)], default=utils.dates.current_year, verbose_name='Год')),
                ('month', models.CharField(choices=[('January', 'Январь'), ('February', 'Февраль'), ('March', 'Март'), ('April', 'Апрель'), ('May', 'Май'), ('June', 'Июнь'), ('July', 'Июль'), ('August', 'Август'), ('September', 'Сентябрь'), ('October', 'Октябрь'), ('November', 'Ноябрь'), ('December', 'Декабрь')], default=utils.dates.current_month, max_length=12, verbose_name='Месяц')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Прогресс строительства',
                'verbose_name_plural': 'Прогрессы строительства',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['title'], 'verbose_name': 'Расположение', 'verbose_name_plural': 'Расположения'},
        ),
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.FileField(blank=True, help_text='Можно загрузить файлы: svg, png, jpg, jpeg', upload_to='project_icons/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])], verbose_name='Иконка'),
        ),
        migrations.CreateModel(
            name='BuildingProgressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='building_progress_images/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('building_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.buildingprogress', verbose_name='Прогресс строительства')),
            ],
            options={
                'verbose_name': 'Изображение прогресса строительства',
                'verbose_name_plural': 'Изображения прогрессов строительства',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='buildingprogress',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_progresses', to='project.project', verbose_name='Проект'),
        ),
    ]
