# Generated by Django 4.2.11 on 2024-05-01 15:12

from django.db import migrations, models
import utils.dates


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_buildingprogress_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingprogress',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=utils.dates.current_month, verbose_name='Месяц'),
        ),
    ]
