# Generated by Django 4.2.11 on 2024-05-02 19:28

from django.db import migrations, models
import utils.dates


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_alter_buildingprogress_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingprogress',
            name='year',
            field=models.IntegerField(default=utils.dates.current_year, verbose_name='Год'),
        ),
    ]
