# Generated by Django 4.2.11 on 2024-05-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_alter_buildingprogress_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='svg_text',
            field=models.TextField(blank=True, verbose_name='Текст SVG'),
        ),
    ]
