# Generated by Django 4.2.11 on 2024-07-03 03:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_icon_svg_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estateobject',
            name='area_max',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Максимальная площадь'),
        ),
        migrations.AlterField(
            model_name='estateobject',
            name='area_min',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Минимальная площадь'),
        ),
    ]
