# Generated by Django 4.2.11 on 2024-06-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_icon_svg_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geotag',
            options={'ordering': ['order'], 'verbose_name': 'Геометка', 'verbose_name_plural': 'Геометки'},
        ),
        migrations.AddField(
            model_name='geotag',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
