# Generated by Django 4.2.14 on 2024-07-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0022_alter_geotag_options_geotag_order"),
        ("project", "0023_alter_image_options_image_order"),
    ]

    operations = []
