# Generated by Django 4.2.7 on 2024-01-28 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_layout_room'),
        ('callback', '0003_confirmreservation_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmreservation',
            name='room',
        ),
        migrations.AddField(
            model_name='confirmreservation',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Проект'),
            preserve_default=False,
        ),
    ]
