# Generated by Django 4.2.11 on 2024-04-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0004_remove_confirmreservation_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон'),
        ),
    ]
